- name: Create Group, User and Deploy the Public Key
  hosts: all
  become: true

  vars:
    group_name:
    - name: testgroup1
    - name: testgroup2
    - name: testgroup3
    - name: testgroup4
    - name: testgroup5
    - name: testgroup6
  
  vars_files:
  - ./add_user.yml
  - ./remove_user.yml
  tasks:

# Creating groups
  - name: Create Groups
    group:
      name: "{{ item.name }}"
    with_items: "{{ group_name }}"

# Create users and add to group 
  - name: Add Users
    user:
      name: add_user
      groups: [user_group_name]

# Set authorized key from file
  - name: Set authorize keys taken from file
    authorized_key:
      user: add_user
      state: present
      key: "{{ lookup('file', './user_public_key.pub') }}"

# Removing user
  - name: Remove Users
    user:
      name: remove_user
      state: absent
      remove: yes 
      force: yes