- name: Create Group, User and Deploy the Public Key
  hosts: all
  become: true
  tasks:

# Create devops group
  - name: Create Groups
    group:
      name: testgorup1

# Creata a user and add to a group
  - name: Add several users
    user:
      name: testuser1
      groups: testgroup1

# Set autrorized key from file
#  - name: Set authorized key taken from file
#   authorized_key:
#    user: serdem
#   state: present
#  key: "{{ lookup('file', '/home/serdem/.ssh/id_rsa.pub') }}"