- name: Create Group, User and Deploy the Public Key
  hosts: all
  become: true

  vars:
    group_name:
    - name: testgroup1
    - name: testgroup2
    - name: testgroup3
    - name: testgroup4
    - name: testgroup5
    - name: testgroup6
  
  vars_files:
  - ./add_user.yml
  - ./remove_user.yml

  tasks:
# Creating groups
  - name: Create Groups
    group:
      name: "{{ item.name }}"
    with_items: "{{ group_name }}"

# Create users and add to group 
  - name: Add Users
    user:
      name: "{{ item.name }}"
      group: "{{ item.group }}"
      state: present
    with_items: 
      - "{{ add_user }}"

# Set autrorized key from file
#  - name: Set authorized key taken from file
#   authorized_key:
#    user: serdem
#   state: present
#  key: "{{ lookup('file', '/home/serdem/.ssh/id_rsa.pub') }}"

# Removing user
  - name: Remove Users
    user:
      name: "{{ item.name }}"
      state: absent
      remove: yes 
      force: yes
    with_items:
      - "{{ remove_user }}"